version: "3.8"

services:
  app:
    build: .
    container_name: vpn_app
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      # персистим конфиги и QR из core/wg/generator.py
      - ./data/configs:/app/configs
      - ./data/qrcodes:/app/qrcodes
      - ./logs:/app/logs
    networks:
      - backend

  db:
    image: postgres:15-alpine
    container_name: vpn_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: vpn_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: vpn_nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8084:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
